#title in header
greet: "Hi Folks."

#main info
#owner
owner: "I am Jin Zhongjia."
email: jinzhongjia@qq.com
info: "Vimer, Gopher, Archlinux User, Open Source Enthusiast"
#description
desc: "This is my personal blog for recording problems and life thoughts, welcome! üòÅ"

#menu
menu:
    Archives: /archives
    About: /About

#index/main page max show posts (in number)
max_post: 8

# cancel user's css
usercss: 

# social profile at the footer/bottom
footer: true
placename: China
placelink: https://en.wikipedia.org/wiki/China
github: https://github.com/jinzhongjia
linkedin:
twitter:
instagram:
stackoverflow:

# favicon
favicon: /images/favicon.ico
# thumbnail
thumbnail: /images/thumbnail.jpg
